---
# bind redis to private network address
redis_bind_interface: "127.0.0.1 {{ internal_ip }}"

# set redis password
redis_requirepass: "{{ vault_redis_password }}"

# cap RAM usage and block eviction
redis_maxmemory: "256mb"
redis_maxmemory_policy: "noeviction"

# make redis append-only
redis_appendonly: "yes"

# disable redis timeout so redis doesn't kill worker connections
redis_timeout: 0
